### ISSUE TITLE
Tab scrolling for macro tags

### ISSUE THREAD

**Issue by foxyblue** [foxyblue/foolscap#152]
e.g. ctrl+left/ctrl+right

To scroll the tabs of macro note libraries.

Might just be sending the `list` command with a macro setting, for a new tab.

```
fscap list -m textbooks
```

**Comment by GiantsLoveDeathMetal** [comment]
[Macro Wiki](https://github.com/GiantsLoveDeathMetal/foolscap/wiki/Macro-tags)
